endpoints:
  hypermedia:
    enabled: true

management:
  context-path: /manage
  security:
    enabled: false

security:
  ignored: /h2-console/**
  
server:
  error:
    whitelabel:
      enabled: false
  port: 13001
  session:
    timeout: 600 # 10 minutes

spring:
  application:
    name: clean-architecture-example
  datasource:
    platform: h2
  jpa:
    generate-ddl: true
    properties:
      hibernate.jdbc.time_zone: UTC